name: Code Quality Analysis

# Trigger the workflow on push, pull request, or manual dispatch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repository URL'
        required: false
        type: string

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run your Python script to analyze the code
      - name: Run code analysis
        run: python analyze-code.py
        env:
          REPO_URL: ${{ github.event.inputs.repo_url || github.repository }} # Use the input repo_url or the default repository

